version: '3.9'
services:
  web:
    build: .
    container_name: event_management_web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python app.py

  db:
    image: mysql:8.0
    container_name: event_management_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: EMS
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ems.sql:/docker-entrypoint-initdb.d/ems.sql

volumes:
  mysql_data: