services:
  web:
    build: .
    container_name: event_management_web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python app.py
    networks:
      - server

  db:
    image: mysql:8.0
    container_name: event_management_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jayapath
      MYSQL_DATABASE: EMS
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ems.sql:/docker-entrypoint-initdb.d/ems.sql
    networks:
      - server

volumes:
  mysql_data:

networks:
  server:
    driver: bridge