- name: Deploy EMS + Mastodon Integration
  hosts: ems_server
  become: true
  vars:
    repo_url: "https://github.com/jayapath1/Event-Management-System"
    project_dir: "/home/ubuntu/Event-Management-System"
    python_version: "3.10"
    mastodon_base_url: "http://localhost:3000"
    mastodon_access_token: "k1L3o4914RbKq5djtJaJud-3dG6-EGDUocu2nG_Kkf8"
    mysql_root_password: "12345"

  tasks:

  # System Update & Dependencies
  - name: Update & upgrade apt packages
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install system dependencies
    apt:
      name:
        - git
        - docker.io
        - docker-compose
        - python3
        - python3-pip
        - mysql-client
        - mysql-server
      state: present

  - name: Ensure Docker service is started
    service:
      name: docker
      state: started
      enabled: yes

  # Project Setup
  - name: Ensure project directory exists
    file:
      path: "{{ project_dir }}"
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0755'

  - name: Clone EMS repository
    git:
      repo: "{{ repo_url }}"
      dest: "{{ project_dir }}"
      update: yes

  - name: Install Python requirements
    pip:
      requirements: "{{ project_dir }}/requirements.txt"
      executable: pip3

  # MySQL Setup
  - name: Ensure MySQL service is running
    service:
      name: mysql
      state: started
      enabled: true

  - name: Create EMS database
    mysql_db:
      name: EMS
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Import EMS SQL schema
    command: "mysql -u root -p{{ mysql_root_password }} EMS < {{ project_dir }}/ems.sql"
    args:
      warn: false

  # Docker Setup
  - name: Build & start EMS Docker containers
    community.docker.docker_compose:
      project_src: "{{ project_dir }}"
      state: present
      build: yes
      restarted: yes

  # Mastodon Configuration
  - name: Create config.json for Mastodon
    copy:
      dest: "{{ project_dir }}/config.json"
      content: |
        {
          "MASTODON_BASE_URL": "{{ mastodon_base_url }}",
          "MASTODON_ACCESS_TOKEN": "{{ mastodon_access_token }}"
        }
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Ensure SSH key directory exists
    file:
      path: /home/ubuntu/.ssh
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0700'

  - name: Copy Mastodon SSH key
    copy:
      src: mastodon.pem
      dest: /home/ubuntu/.ssh/mastodon.pem
      owner: ubuntu
      group: ubuntu
      mode: '0600'

  # Create eventmanager user
  - name: Run Mastodon setup script to create eventmanager
    command: "python3 mastodon_integration/mastodon_setup.py"
    args:
      chdir: "{{ project_dir }}"

  - name: Display next steps
    debug:
      msg: |
        EMS + Mastodon deployment completed!!
        - Open EMS: http://127.0.0.1:5001/
        - Open Mastodon (via SSH tunnel if needed): http://localhost:3000/home
        - EMS default credentials:
            * Manager: ucp / ucp123
            * Customer: customer / cust123
        - Check Mastodon integration using mastodon_test.py