apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: applications
spec:
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  interval: 5m
  chart:
    spec:
      chart: mastodon
      version: 13.0.9
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: applications
  values:
    localDomain: "cyberlab.mastodon"
    webDomain: "cyberlab.mastodon"
    enableSearches: true
    enableS3: true
    adminUser: "CyberlabAdmin"
    adminEmail: "cyberlab@mastodon.com"
    adminPassword: "password"
    activeRecordEncryptionDeterministicKey: "3fY9dooK1YklB4qWXDWJ0WuuHtFcixP5"
    activeRecordEncryptionKeyDerivationSalt: "4hHIqySX9JHr2P6lyCjSwFLNANe38LYP"
    activeRecordEncryptionPrimaryKey: "CO0iCiPsDTxYaDEcPvVkWG1lbME3csJH"
    otpSecret: "k3c9i6d7k8jfi9s0n8l2p7a6s3j0d9q1"
    secretKeyBase: "6fY9dooK1YklB4qWXDWJ0WuuHtFcixP5"
    
    persistence:
      enabled: true
      size: 8Gi
      storageClass: longhorn 

    redis:
      enabled: true 
      master:
        persistence:
          size: 2Gi

    elasticsearch:
      data:
        persistence:
          size: 8Gi
      master:
        persistence:
          size: 2Gi
    
    postgresql:
      enabled: true
      persistence:
        size: 8Gi
      auth:
        username: bn_mastodon
        password: ""
        database: mastodon_production
        existingSecret: ""
      architecture: standalone
      primary:
        service:
          ports:
            postgresql: 5432

    minio:
      enabled: true
      auth:
        rootUser: admin
        rootPassword: password
      persistence:
        enabled: true
        size: 8Gi
        storageClass: longhorn

    # externalDatabase:
    #   host: postgres-postgresql.applications.svc.cluster.local
    #   port: 5432
    #   user: postgres
    #   existingSecret: postgres-secret
    #   existingSecretPasswordKey: postgres-password
    #   database: mastodon_production

    s3:
      endpoint: http://minio.applications.svc.cluster.local:9000
      bucket: mastodon-media
      region: us-east-1
      forcePathStyle: true
      existingSecret: minio-creds
      existingSecretAccessKey: accessKey
      existingSecretSecretKey: secretKey

    initJob:
      migrateAndCreateAdmin:
        enabled: true
        migrateDB: true
        migrateElasticsearch: false
        createAdmin: true

    web:
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 1Gi

    waitForS3:
      tlsSkipVerify: true
